"""baseline schema

Revision ID: bdd7c2231e7c
Revises: 
Create Date: 2026-09-18 13:55:38.886959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd7c2231e7c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('invite_token', sa.String(length=128), nullable=True),
    sa.Column('invite_expires_at', sa.DateTime(), nullable=True),
    sa.Column('invited_by_id', sa.Integer(), nullable=True),
    sa.Column('monthly_budget_usd', sa.Float(), nullable=False),
    sa.Column('period_started_on', sa.Date(), nullable=True),
    sa.Column('period_spend_usd', sa.Float(), nullable=False),
    sa.Column('lifetime_spend_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_invite_token'), ['invite_token'], unique=True)

    op.create_table('career_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('links', sa.JSON(), nullable=False),
    sa.Column('headline', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('intake_notes', sa.Text(), nullable=False),
    sa.Column('open_questions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('career_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_career_profile_user_id'), ['user_id'], unique=False)

    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('relationship_note', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('how_known', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_user_id'), ['user_id'], unique=False)

    op.create_table('google_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_json', sa.Text(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('account_email', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('google_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_google_token_user_id'), ['user_id'], unique=True)

    op.create_table('intake_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intake_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intake_message_user_id'), ['user_id'], unique=False)

    op.create_table('job_posting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_name', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('jd_text', sa.Text(), nullable=False),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_posting_user_id'), ['user_id'], unique=False)

    op.create_table('job_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ats', sa.String(length=40), nullable=False),
    sa.Column('board_token', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('last_job_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ats', 'board_token', name='uq_source_user_board')
    )
    with op.batch_alter_table('job_source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_source_user_id'), ['user_id'], unique=False)

    op.create_table('llm_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('prompt_name', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('llm_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_cache_user_id'), ['user_id'], unique=False)

    op.create_table('sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_sync_user_key')
    )
    with op.batch_alter_table('sync_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_state_user_id'), ['user_id'], unique=False)

    op.create_table('aspiration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('target_titles', sa.JSON(), nullable=False),
    sa.Column('target_industries', sa.JSON(), nullable=False),
    sa.Column('target_companies', sa.JSON(), nullable=False),
    sa.Column('locations', sa.JSON(), nullable=False),
    sa.Column('remote_preference', sa.String(length=40), nullable=False),
    sa.Column('comp_min', sa.Float(), nullable=False),
    sa.Column('comp_max', sa.Float(), nullable=False),
    sa.Column('comp_currency', sa.String(length=8), nullable=False),
    sa.Column('non_negotiables', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=False),
    sa.Column('issued_on', sa.String(length=32), nullable=False),
    sa.Column('credential_id', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(length=200), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('field', sa.String(length=200), nullable=False),
    sa.Column('end_year', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.String(length=32), nullable=False),
    sa.Column('end_date', sa.String(length=32), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('responsibilities', sa.JSON(), nullable=False),
    sa.Column('achievements', sa.JSON(), nullable=False),
    sa.Column('scope_change_note', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tech', sa.JSON(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('highlight', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('flavor', sa.String(length=80), nullable=False),
    sa.Column('is_master', sa.Boolean(), nullable=False),
    sa.Column('source_filename', sa.String(length=300), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('ats_score', sa.Float(), nullable=False),
    sa.Column('ats_report', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_variant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_variant_user_id'), ['user_id'], unique=False)

    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('proficiency', sa.String(length=40), nullable=False),
    sa.Column('years', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('resume_variant_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_report', sa.JSON(), nullable=False),
    sa.Column('gap_report', sa.JSON(), nullable=False),
    sa.Column('tailored_resume_md', sa.Text(), nullable=False),
    sa.Column('cover_letter_text', sa.Text(), nullable=False),
    sa.Column('talking_points', sa.JSON(), nullable=False),
    sa.Column('tailoring_meta', sa.JSON(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('quality_report', sa.JSON(), nullable=False),
    sa.Column('quality_verdict', sa.String(length=20), nullable=False),
    sa.Column('gate_override_reason', sa.Text(), nullable=False),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_posting.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_variant_id'], ['resume_variant.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_user_id'), ['user_id'], unique=False)

    op.create_table('application_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=300), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_event_source_external')
    )
    op.create_table('discovered_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=False),
    sa.Column('employment_type', sa.String(length=60), nullable=False),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('jd_text', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('keyword_score', sa.Float(), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=False),
    sa.Column('closeable_score', sa.Float(), nullable=False),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.Column('is_deep_scored', sa.Boolean(), nullable=False),
    sa.Column('match_report', sa.JSON(), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('adopted_application_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adopted_application_id'], ['application.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['job_source.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_id', 'external_id', name='uq_discovered_external')
    )
    with op.batch_alter_table('discovered_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovered_job_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_job_user_id'), ['user_id'], unique=False)

    op.create_table('interview_prep_brief',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('company_snapshot', sa.Text(), nullable=False),
    sa.Column('likely_questions', sa.JSON(), nullable=False),
    sa.Column('star_stories', sa.JSON(), nullable=False),
    sa.Column('technical_focus', sa.JSON(), nullable=False),
    sa.Column('salary_briefing', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outreach_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('variant', sa.String(length=40), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_on', sa.Date(), nullable=True),
    sa.Column('reply_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.JSON(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['interview_prep_brief.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practice_session')
    op.drop_table('outreach_message')
    op.drop_table('interview_prep_brief')
    with op.batch_alter_table('discovered_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovered_job_user_id'))
        batch_op.drop_index(batch_op.f('ix_discovered_job_source_id'))

    op.drop_table('discovered_job')
    op.drop_table('application_event')
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_user_id'))

    op.drop_table('application')
    op.drop_table('skill')
    with op.batch_alter_table('resume_variant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_variant_user_id'))

    op.drop_table('resume_variant')
    op.drop_table('portfolio_project')
    op.drop_table('experience')
    op.drop_table('education')
    op.drop_table('certification')
    op.drop_table('aspiration')
    with op.batch_alter_table('sync_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_state_user_id'))

    op.drop_table('sync_state')
    with op.batch_alter_table('llm_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_cache_user_id'))

    op.drop_table('llm_cache')
    with op.batch_alter_table('job_source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_source_user_id'))

    op.drop_table('job_source')
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_posting_user_id'))

    op.drop_table('job_posting')
    with op.batch_alter_table('intake_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intake_message_user_id'))

    op.drop_table('intake_message')
    with op.batch_alter_table('google_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_google_token_user_id'))

    op.drop_table('google_token')
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_user_id'))

    op.drop_table('contact')
    with op.batch_alter_table('career_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_career_profile_user_id'))

    op.drop_table('career_profile')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_invite_token'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
