"""store uploaded resume bytes

Revision ID: fec8cd446402
Revises: bdd7c2231e7c
Create Date: 2026-09-18 14:03:19.613786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec8cd446402'
down_revision: Union[str, Sequence[str], None] = 'bdd7c2231e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_variant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stored_bytes', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_variant', schema=None) as batch_op:
        batch_op.drop_column('stored_bytes')

    # ### end Alembic commands ###
